### ISSUE TITLE
Simulate heat diffusion

### ISSUE THREAD

**Issue by laurentperrinet** [pmocz/latticeboltzmann-python#1]
Is it possible to add a way to simulate the diffusion of a hot flow of air in a colder one?

**Comment by pmocz** [comment]
Yes. Here, the isothermal Navier-Stokes are simulated. But it is possible to add heat transfer by introducing a second distribution function, g, for the internal energy density. Conceptually, evolving g is the same as evolving the density distribution function f. See Section 2.3 of the review paper linked here for how to do this:
https://www.sciencedirect.com/science/article/pii/S1110016815001362 for details

I encourage others to fork and augment the code.
