### ISSUE TITLE
Collision implementation

### ISSUE THREAD

**Issue by Janos95** [pmocz/latticeboltzmann-python#5]
In the collision step it looks like the python code uses `ux * ux + uy * uy = dot(u, u)`
https://github.com/pmocz/latticeboltzmann-python/blob/e85dd009cf57f548b733864e0e9b661160783b67/latticeboltzmann.py#L74
In comparison in the equation in your medium post, the collision expression uses `dot(u,u)^2`:
![image](https://user-images.githubusercontent.com/19853534/204106630-dc5f13bc-0005-4f77-b741-e649d6381fd3.png)
Am I missing something or is the code missing a square?

On a different note, thanks for the great work on the small,  self-contained simulation examples, they are very educational.

**Comment by Janos95** [comment]
Looking a bit more into it, I think the formula in the the blogpost might be wrong?

**Comment by pmocz** [comment]
Great catch @Janos95 ! There is a typo in the writeup. The (u.u) term in the collision expression is not supposed to be squared. I am correcting the blog post
