### ISSUE TITLE
Simulation values are getting smaller over time

### ISSUE THREAD

**Issue by HamidGadirov** [pmocz/latticeboltzmann-python#6]
Hi, 
I noticed that while the simulation continues the values of the flow field are getting smaller and smaller. That is the case if I use e.g. 10K time steps of the simulation. Why is that so? Is it meant to be this way? I wanted to use this data in my project related to flow learning via neural networks and values which are becoming very small is somewhat problematic.

**Comment by pmocz** [comment]
This is the vorticity field after 10,000 steps: 

![image](https://user-images.githubusercontent.com/7489877/224209102-23a6c725-08d7-4b37-b719-1a5e272b5c4b.png)

The mean velocity (ux) changes from 0.18 at cycle 0 to 0.024 at cycle 9999

In this problem, I used periodic boundary conditions, so the flow will slow down with time as the fluid hits the cylinder. The result is expected.

You may wish to implement inflow/outflow boundary conditions to have sustained motion
