### ISSUE TITLE
Changing the Reynolds number of the simulation

### ISSUE THREAD

**Issue by HamidGadirov** [pmocz/latticeboltzmann-python#7]
Hi @pmocz ,
I wanted to change the Reynolds number of the simulation to create an ensemble with e.g. Re from 50 to 250. I know the Reynolds number equation but am not sure which variables to change in the code, e.g. dynamic viscosity, fluid velocity, or fluid density. I tried to change the average density (`rho0`) but it didn't affect the flow. What is the best way to change the Reynolds number in this simulation? For now, I only managed to modify the flow by changing the cylinder boundary parameters.

**Comment by pmocz** [comment]
Try varying the collision timescale (tau)
